name: T-minus 30 days checklist
description: This release checklist tracks the initial setup of a new Knative release.
title: "[Release vx.xx]: T-minus 30 days checklist"
assignees:
  - knative-release-leads
body:
- id: release-1
  type: checkboxes
  attributes:
    label: Please change the title to include the current release.
    description: |
      - This release checklist tracks the initial setup of a new Knative release.
      - View [documentation](https://github.com/knative/release/blob/main/PHASES.md#t-minus-30-days).
    options:
      - label: Prior release leads have been removed from rotation
      - label: New release leads have been added for the new rotation
      - label: A new Slack channel for the release has been created
      - label: A new GitHub issue for the "T-minus 14 days checklist" has been created
