name: T-minus 7 days checklist
description: This release checklist tracks the release of the supporting repos and other timely actions.
title: "[Release vx.xx]: T-minus 7 days checklist"
assignees:
  - knative-release-leads
body:
- id: release-3
  type: checkboxes
  attributes:
    label: Please change the title to include the current release.
    description: |
      - This release checklist tracks the release of the supporting repos and other timely actions.
      - Please only mark a repo as done after it has had its release branch cut.
      - View [documentation](https://github.com/knative/release/blob/main/PHASES.md#t-minus-7-days).
    options:
      - label: All items on the "T-minus 14 days checklist" have been checked off
        required: true
      - label: A fresh HackMD release notes document has been pinned to the **#*release-xdotx** Slack channel
      - label: An announcement has been made in the **#general** Slack channel that the cut of `pkg` is immminent
      - label: The nightly release build status has been verified for each of the core knative.dev repos
      - label: knative.dev/hack
      - label: knative.dev/pkg
      - label: knative.dev/networking
      - label: knative.dev/caching
      - label: knative.dev/reconciler-test
      - label: knative.dev/control-protocol
      - label: A new GitHub issue for the "T-minus 1 day checklist" has been created