name: 1 day prior to release checklist
description: This release checklist includes checks to ensure the release is ready to start.
title: "[Release vx.xx]: 1 day prior to release checklist"
assignees:
  - knative-release-leads
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please mark each task as they get done.
    description: |
      - Please change the title to include the current release.
      - See the full [release instructions](https://github.com/knative/release/blob/main/INSTRUCTIONS.md) for details.
    options:
      - label: All items on the "7 days prior - first batch of repos checklist" have been checked off
        required: true
      - label: Obtained ACK from each WG leads that the release is imminent and is green-lighted
      - label: Nighly builds are passing for each repo on the [list of nightly builds](https://github.com/knative/release/blob/main/README.md#repo-releasability)
      - label: A new GitHub issue for the "Release - second batch of repos checklistt" has been created