name: T-minus 1 day checklist
description: This release checklist includes checks to ensure the release is ready to start.
title: "[Release vx.xx]: T-minus 1 day checklist"
assignees:
  - knative-release-leads
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please change the title to include the current release.
    description: |
      - This release checklist includes checks to ensure the release is ready to start.
      - View [documentation](https://github.com/knative/release/blob/main/PHASES.md#t-minus-1-days).
    options:
      - label: All items on the "T-minus 7 days checklist" have been checked off
        required: true
      - label: Obtained ACK from each WG leads that the release is imminent and is green-lighted
      - label: Nighly builds are passing for each repo on the [list of nightly builds](https://github.com/knative/release/blob/main/README.md#repo-releasability)
      - label: A new GitHub issue for the "T-minus zero first batch checklist" has been created