name: Release - second batch of repos checklist
description: This release checklist tracks the first batch of repos to be released.
title: "[Release vx.xx]: second batch of repos checklist"
assignees:
  - knative-release-leads
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please mark each task as they get done.
    description: |
      - Please change the title to include the current release.
      - See the full [release instructions](https://github.com/knative/release/blob/main/INSTRUCTIONS.md) for details.
      - Please ensure that there are no outstanding PRs for each repo before cutting its release branch.
      - Note that it is not required that all repos be released on the same day the release is scheduled to start.
      - Follow the specific instructions to [release a repository](https://github.com/knative/release/blob/main/INSTRUCTIONS.md#release-a-repository) for each repo listed.
    options:
      - label: All items on the "1 Day Prior to Release Checklist" have been checked off
        required: true
      - label: knative.dev/serving
      - label: knative.dev/net-certmanager
      - label: knative.dev/net-contour
      - label: knative.dev/net-http01
      - label: knative.dev/net-istio
      - label: knative.dev/net-kourier
      - label: knative.dev/net-gateway-api
      - label: knative.dev/eventing
      - label: knative.dev/sample-controller
      - label: A new GitHub issue for the "Release - third batch of repos checklist" has been created