name: T-minus zero first batch checklist
description: This release checklist tracks the first batch of core repos to be released.
title: "[Release vx.xx]: T-minus zero first batch checklist"
assignees:
  - knative-release-leads
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please change the title to include the current release.
    description: |
      - This release checklist tracks the first batch of core repos to be released.
      - Please only mark a repo as done after it has been verified the release has been published. Release notes can be done later.
      - View [documentation](https://github.com/knative/release/blob/main/PHASES.md#t-minus-zero-first-batch).
    options:
      - label: All items on the "T-minus 1 day checklist" have been checked off
        required: true
      - label: knative.dev/serving
      - label: knative.dev/net-certmanager
      - label: knative.dev/net-contour
      - label: knative.dev/net-http01
      - label: knative.dev/net-istio
      - label: knative.dev/net-kourier
      - label: knative.dev/net-gateway-api
      - label: knative.dev/eventing
      - label: knative.dev/sample-controller
      - label: A new GitHub issue for the "T-minus zero second batch checklist" has been created