name: Release - fourth batch of repos checklist
description: xxx.
title: "[Release vx.xx]: Third Batch of Repos Checklist"
assignees:
  - knative-release-leads
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please mark each task as they get done.
    description: |
      - Please change the title to include the current release.
      - See the full [release instructions](https://github.com/knative/release/blob/main/INSTRUCTIONS.md) for details.
      - Please ensure that there are no outstanding PRs for each repo before cutting its release branch.
      - Note that it is not required that all repos be released on the same day the release is scheduled to start.
      - Follow the specific instructions to [release a repository](https://github.com/knative/release/blob/main/INSTRUCTIONS.md#release-a-repository) for each repo listed.
    options:
      - label: All items on the "Release - third batch of repos checklistt" have been checked off
        required: true
      - label: knative.dev/client
      - label: knative.dev/eventing-kafka
      - label: knative.dev/eventing-redis
      - label: knative.dev/eventing-github
      - label: knative.dev/eventing-gitlab
      - label: A new GitHub issue for the "Release - last batch of repos checklist" has been created