name: Release - last batch of repos checklist
description: xxx
title: "[Release vx.xx]: last batch of repos checklist"
assignees:
  - knative-release-leads
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please mark each task as they get done.
    description: |
      - Please change the title to include the current release.
      - See the full [release instructions](https://github.com/knative/release/blob/main/INSTRUCTIONS.md) for details.
      - Please ensure that there are no outstanding PRs for each repo before cutting its release branch.
      - Note that it is not required that all repos be released on the same day the release is scheduled to start.
      - For each repo listed:
        - follow the specific instructions to [release a repository](https://github.com/knative/release/blob/main/INSTRUCTIONS.md#release-a-repository).
        - wait for the [release automation ](https://github.com/knative/release/blob/main/INSTRUCTIONS.md#release-a-repository) to kick in (runs on a 2 hour interval) and create the release tag.
        - use the GitHub UI to edit the tag to include the collected release-notes.
    options:
      - label: All items on the "Release - fourth batch of repos checklist" have been checked off
        required: true
      - label: knative.dev/eventing-kafka-broker
      - label: knative.dev/eventing-autoscaler-keda
      - label: knative.dev/kn-plugin-admin
      - label: knative.dev/kn-plugin-event
      - label: knative.dev/kn-plugin-source-kafka
      - label: knative.dev/kn-plugin-source-kamelet
      - label: knative.dev/kn-plugin-quickstart
      - label: A new GitHub issue for the "XXX" has been created