name: Post release checklist
description: This release checklist tracks the work to be done post release.
title: "[Release vx.xx]: Post release checklist"
assignees:
  - knative-release-leads
body:
- id: release-4
  type: checkboxes
  attributes:
    label: Please change the title to include the current release.
    description: |
      - This release checklist tracks the work to be done post release.
      - View [documentation](https://github.com/knative/release/blob/main/PHASES.md#post-release).
    options:
      - label: All items on the "T-minus zero first last batch checklist" have been checked off
        required: true


# Pin issue: https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository


# - [ ] All items on the "Day of Release Checklist" have been checked off
# - [ ] homebrew-client updated
# - [ ] homebrew-kn-plugins updated
# - [ ] Add the release to the [release table](https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md)
# - [ ] Watch for the PR like [this one](https://github.com/knative/test-infra/pull/2670) to enable dot releases on the new releases and approve it. These are create by the Prow https://prow.knative.dev/?job=ci-knative-prow-jobs-syncer
# - [ ] Send a PR like [this one](https://github.com/knative-sandbox/knobots/pull/87) to bump knobots auto release workflow to the next release.


