name: Knative release tasks checklist
description: This checklist tracks the tasks to be done for a new Knative release.
title: "[Release vx.xx]: Release tasks checklist"
assignees:
  - knative-release-leads
body:
- id: release-tasks
  type: checkboxes
  attributes:
    label: Please change the title to include the current release.
    description: |
      - This checklist tracks the tasks to be done for a new Knative release.
    options:
      - label: T-minus 30 days - Prior release leads have been removed from rotation
      - label: T-minus 30 days - New release leads have been added for the new rotation
      - label: T-minus 30 days - A new Slack channel for the release has been created
      - label: T-minus 14 days - The releasability defaults have been updated
      - label: T-minus 14 days - The releasability defaults update have been propagated thru all applicable `knative.dev` repos
      - label: T-minus 14 days - An announcement has been made in the **#general** Slack channel that `pkg` will be released in a week
      - label: T-minus 7 days - A fresh HackMD release notes document has been pinned to the **#*release-xdotx** Slack channel
      - label: T-minus 7 days - A draft for the announcement blog post has been started
      - label: T-minus 7 days - An announcement has been made in the **#general** Slack channel that the cut of `pkg` is immminent
      - label: T-minus 7 days - The nightly release build status has been verified for each of the core knative.dev repos
      - label: T-minus 1 day - Obtained ACK from each WG leads that the release is imminent and is green-lighted
      - label: T-minus 1 day - A re-check of the nightly release build status has been done for each of the core knative.dev repos
      - label: Post release - Homebrew tap has been updated
      - label: Post release - The client plugin's Homebrew repo has been updated
      - label: Post release - Release schedule has been updated
      - label: Post release - An announcement was made in the **#general** and **#operation** Slack channels that the new Knative release is out
      - label: A blog post announcing the release has been published
